-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ai_generation_drafts
(
    id bigserial NOT NULL,
    generation_type text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::text,
    input_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    output_payload jsonb,
    error_text text COLLATE pg_catalog."default",
    requested_by bigint,
    model_used text COLLATE pg_catalog."default",
    fallback_chain jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    completed_at timestamp with time zone,
    CONSTRAINT ai_generation_drafts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_generation_logs
(
    id bigserial NOT NULL,
    draft_id bigint,
    requested_by bigint,
    model text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    error_text text COLLATE pg_catalog."default",
    prompt_tokens integer,
    completion_tokens integer,
    duration_ms integer NOT NULL DEFAULT 0,
    request_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    response_payload jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ai_generation_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.course_assignments
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    course_id bigint NOT NULL,
    assigned_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT course_assignments_pkey PRIMARY KEY (id),
    CONSTRAINT course_assignments_user_id_course_id_key UNIQUE (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS public.course_learning_items
(
    id bigserial NOT NULL,
    course_id bigint NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    text text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT course_learning_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.courses
(
    id bigserial NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    full_description text COLLATE pg_catalog."default",
    category text COLLATE pg_catalog."default" NOT NULL,
    level text COLLATE pg_catalog."default" NOT NULL,
    instructor text COLLATE pg_catalog."default",
    duration integer NOT NULL DEFAULT 0,
    image text COLLATE pg_catalog."default",
    audience text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT courses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.departments
(
    id bigserial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT departments_pkey PRIMARY KEY (id),
    CONSTRAINT departments_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.lesson_progress
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    course_id bigint NOT NULL,
    lesson_id bigint NOT NULL,
    completed boolean NOT NULL DEFAULT false,
    score integer NOT NULL DEFAULT 0,
    completed_at timestamp with time zone,
    CONSTRAINT lesson_progress_pkey PRIMARY KEY (id),
    CONSTRAINT lesson_progress_user_id_lesson_id_key UNIQUE (user_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS public.lesson_questions
(
    id bigserial NOT NULL,
    lesson_id bigint NOT NULL,
    sort_order integer NOT NULL DEFAULT 1,
    question text COLLATE pg_catalog."default" NOT NULL,
    options jsonb NOT NULL DEFAULT '[]'::jsonb,
    correct_index integer DEFAULT 0,
    question_type text COLLATE pg_catalog."default" NOT NULL DEFAULT 'single'::text,
    correct_indices jsonb NOT NULL DEFAULT '[]'::jsonb,
    matching_pairs jsonb NOT NULL DEFAULT '[]'::jsonb,
    explanation text COLLATE pg_catalog."default",
    points integer NOT NULL DEFAULT 1,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT lesson_questions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lessons
(
    id bigserial NOT NULL,
    course_id bigint NOT NULL,
    sort_order integer NOT NULL DEFAULT 1,
    title text COLLATE pg_catalog."default" NOT NULL,
    duration integer NOT NULL DEFAULT 0,
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    video_url text COLLATE pg_catalog."default",
    CONSTRAINT lessons_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.positions
(
    id bigserial NOT NULL,
    department_id bigint NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT positions_pkey PRIMARY KEY (id),
    CONSTRAINT positions_department_id_name_key UNIQUE (department_id, name)
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    token text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT refresh_tokens_token_key UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.schema_migrations
(
    id bigserial NOT NULL,
    filename text COLLATE pg_catalog."default" NOT NULL,
    applied_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT schema_migrations_pkey PRIMARY KEY (id),
    CONSTRAINT schema_migrations_filename_key UNIQUE (filename)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role text COLLATE pg_catalog."default" NOT NULL DEFAULT 'user'::text,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::text,
    phone text COLLATE pg_catalog."default",
    "position" text COLLATE pg_catalog."default",
    department text COLLATE pg_catalog."default",
    company text COLLATE pg_catalog."default",
    bio text COLLATE pg_catalog."default",
    notifications jsonb NOT NULL DEFAULT '{"progress": true, "deadlines": false, "newCourses": true, "systemNews": true, "certificates": true, "courseUpdates": true, "systemUpdates": true}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    department_id bigint,
    position_id bigint,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.ai_generation_drafts
    ADD CONSTRAINT ai_generation_drafts_requested_by_fkey FOREIGN KEY (requested_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.ai_generation_logs
    ADD CONSTRAINT ai_generation_logs_draft_id_fkey FOREIGN KEY (draft_id)
    REFERENCES public.ai_generation_drafts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ai_generation_logs
    ADD CONSTRAINT ai_generation_logs_requested_by_fkey FOREIGN KEY (requested_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.course_assignments
    ADD CONSTRAINT course_assignments_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course_assignments
    ADD CONSTRAINT course_assignments_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course_learning_items
    ADD CONSTRAINT course_learning_items_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_progress
    ADD CONSTRAINT lesson_progress_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_progress
    ADD CONSTRAINT lesson_progress_lesson_id_fkey FOREIGN KEY (lesson_id)
    REFERENCES public.lessons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_progress
    ADD CONSTRAINT lesson_progress_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lesson_questions
    ADD CONSTRAINT lesson_questions_lesson_id_fkey FOREIGN KEY (lesson_id)
    REFERENCES public.lessons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_lesson_questions_lesson
    ON public.lesson_questions(lesson_id);


ALTER TABLE IF EXISTS public.lessons
    ADD CONSTRAINT lessons_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.positions
    ADD CONSTRAINT positions_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.departments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.departments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_position_id_fkey FOREIGN KEY (position_id)
    REFERENCES public.positions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;